#!/bin/bash

echo "Running..."

set -e

    AUTH="INSERT-AUTH-TOKEN"

    #RUN_ONE=".\\reports\\run-1.json"
    #RUN_TWO=".\\reports\\run-2.json"
    #RUN_THREE=".\\reports\\run-3.json"
    #RUN_FOUR=".\\reports\\run-4.json"

echo "Have you retrieved your uaa auth token? (y/n)"
read input

if [ $input == "n" ]; then
    echo "Please retrieve your uaa-auth token, insert it in the run script, and rerun the script..."
    exit

else if [ $input == "y" ]; then
    #### SAMPLE RUN REPORT COMMANDS ####
    # echo "Starting the kibana script for APP-NAME - Prod APP ERROR Checks..."
    # python kibana_report_downloader.py --report_file=$RUN_NUMBER --auth=$AUTH
    #
    # echo "Completed kibana script..."
    #

    ######################################
    ## APP-NAME - Prod APP ERROR Checks ##
    ######################################

    echo "Starting the kibana script for APP-NAME - Prod APP ERROR Checks..."
    python kibana_report_downloader.py --report_file=$RUN_ONE --auth=$AUTH

    echo "Completed kibana script..."

    ##########################################
    ## APP-NAME - Prod CELL DESTROYED Audit ##
    ##########################################
    echo "Starting the kibana script for APP-NAME - Prod CELL DESTROYED Audit..."
    python kibana_report_downloader.py --report_file=$RUN_TWO --auth=$AUTH

    echo "Completed kibana script..."

    ###################################
    ## APP-NAME - Staging STG Checks ##
    ###################################
    echo "Starting the kibana script for APP-NAME - Staging STG Checks..."
    python kibana_report_downloader.py --report_file=$RUN_THREE --auth=$AUTH

    echo "Completed kibana script..."

    ################################
    ## APP-NAME - Prod RTR Checks ##
    ################################
    echo "Starting the kibana script for APP-NAME - Prod RTR Checks..."
    python kibana_report_downloader.py --report_file=$RUN_FOUR --auth=$AUTH

    echo "Completed kibana script..."

else if [ $input != "n" ] || [ $input != "y" ]; then
    echo "Please insert y or n. Exiting..."
    exit
fi
fi
fi
